name: widget_library
description: A Flutter widget library with a custom button component.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
